vulntron:
  save_json: true
  run_type: "auto"
  cluster_URL: "https://api.crc-eph.r9lp.p1.openshiftapps.com:6443"
  logging: 
    stdout: true
    log_file: true
    log_file_location: "/tmp/vulntron/log/"
    log_file_name: ""

# syft configuration
syft:
  db_root_dir: "/tmp/vulntron/"
  validate_by_hash_on_get: false

# grype configuration
grype:
  db_root_dir: "/tmp/vulntron/"
  listing_url: "https://toolbox-data.anchore.io/grype/databases/listing.json"
  validate_by_hash_on_get: false
  
defect_dojo:
  url: "http://localhost:8080"
  username: "admin"
  password: "Password1."
  enable_deduplication: true
  delete_duplicates: true
  max_duplicates: 0
  