# Vulntron tool general config
vulntron:
  run_type: "auto"
  cluster_URL: "https://api.crc-eph.r9lp.p1.openshiftapps.com:6443"
  logging: 
    stdout: true
    log_file: true
    log_file_location: "/tmp/vulntron/log/"
    log_file_name: ""

# DefectDojo specific config
defect_dojo:
  enable_deduplication: true
  delete_duplicates: true
  max_duplicates: 0
  slack_notifications: true

# Scanner types config
scan_types:
  - name: "Anchore Grype"
    engName: "Grype_eng"
    function: "RunGrype"
    enabled: true
  - name: "Trivy Scan"
    engName: "Trivy_eng"
    function: "RunTrivy"
    enabled: true


# Additional scanner config
# syft configuration
syft:
  db_root_dir: "/tmp/vulntron/"
  
# grype configuration
grype:
  db_root_dir: "/tmp/vulntron/"
  listing_url: "https://toolbox-data.anchore.io/grype/databases/listing.json"
  validate_by_hash_on_get: false
    