apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulntron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulntron
  template:
    metadata:
      labels:
        app: vulntron
    spec:
      containers:
      - name: vulntron
        image: quay.io/rhn_support_mfindra/vulntron:1.8
        ports:
        - containerPort: 8088
        env:
        - name: DEFECT_DOJO_URL
          value: "http://defectdojo-vulntron.apps.crc-eph.r9lp.p1.openshiftapps.com"
        - name: DEFECT_DOJO_USERNAME
          value: "admin"
        - name: DEFECT_DOJO_PASSWORD
          value: ""
        - name: DEFECT_DOJO_TOKEN
          value: ""
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: vulntronbot-token-rs7cx
              optional: false
        - name: OC_NAMESPACE_LIST
          value: "ephemeral-4svsur"
      serviceAccount: vulntronbot
        