apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulntron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulntron
  template:
    metadata:
      labels:
        app: vulntron
    spec:
      containers:
      - name: vulntron
        image: quay.io/rhn_support_mfindra/vulntron:1.6
        ports:
        - containerPort: 8088
        env:
        - name: DEFECT_DOJO_URL
          value: "http://localhost:8080"
        - name: DEFECT_DOJO_USERNAME
          value: "admin"
        - name: DEFECT_DOJO_PASSWORD
          value: "Password1."
        - name: DEFECT_DOJO_TOKEN
          value: ""
        - name: OC_TOKEN
          value: ""